### ISSUE TITLE
Cant connect to hub any help please

### ISSUE THREAD

**Issue by spacesound** [luadch/announcer_client#8] opened 2020-07-11 22:34 UTC
hello wen try to conect give me this error

[2020-07-11/23:32:47] Try to connect to hub...
[2020-07-11/23:32:50] Connected. Try a SSL handshake...
[2020-07-11/23:32:50] Fail: tlsv1 alert protocol version
[2020-07-11/23:32:50] Announcer stopped. (Killed process: 6848)
[2020-07-11/23:32:50] Luadch Announcer Client v0.8 ready.

also sometimes this one

[2020-07-11/23:32:29] Try to connect to hub...
[2020-07-11/23:32:32] invalid table
[2020-07-11/23:32:32] invalid table
[2020-07-11/23:32:32] 
[2020-07-11/23:32:32] Unlock 'Tab 1' controls
[2020-07-11/23:32:32] Unlock 'Tab 2' controls
[2020-07-11/23:32:32] Unlock 'Tab 3' controls
[2020-07-11/23:32:32] Unlock 'Tab 4' controls
[2020-07-11/23:32:32] Unlock 'Tab 5' controls
[2020-07-11/23:32:33] Unlock 'Tab 6' controls

please i need someone to help me and conect announcer to hub thanks

**Comment by Sopor** [comment] 2020-07-11 23:03
What version of Luadch are you running?

The Announcer is not compatible with latest Luadch.

You also need to generate a cert for the Announcer to use. You can do it with [this tool](https://github.com/luadch/certmanager/releases).

**Comment by spacesound** [comment] 2020-07-11 23:47
can you please add me somewere for we talk direct?

**Comment by spacesound** [comment] 2020-07-11 23:48
yes i put inside luadch folder the client announce after with certmanager i generate key for cert folder from announce

**Comment by spacesound** [comment] 2020-07-11 23:50
i have luadch v2.21 and announcer client v08

**Comment by spacesound** [comment] 2020-07-11 23:51
im using windows 10

**Comment by spacesound** [comment] 2020-07-11 23:56
so please what version will work? and now i will lost all scripts and setup that i have in this luadchor can i copy script folders , big problem now dont work with last version

**Comment by spacesound** [comment] 2020-07-12 01:33
thanks alot i change to version v20 and is working perfect :) many thanks ,SOLVED

**Comment by Sopor** [comment] 2020-07-12 01:33
So it has never worked for you? This is your first attempt to connect the Announcer to Luadch 2.21? I haven't tried 2.21 but i know it will not work with Luadch 2.22 RC3.

The Announcer will not support TLS v1.3 either so if you use that you need to change it to TLS v1.2.

You also need to copy these four files to the Announcers cert folder: `cacert.pem, cakey.pem, servercert.pem, serverkey.pem`

**Comment by Sopor** [comment] 2020-07-12 17:12
If the issue is solved you should close it!

**Comment by spacesound** [comment] 2020-07-12 17:42
Problem SOLVED

**Closed as completed** 2020-07-12 17:42 UTC
